import type { NextPage } from 'next'
import Head from 'next/head'
// next/router  https://nextjs.org/docs/api-reference/next/router
// import { useRouter } from 'next/router'
import { useAppContext } from '../context/AppContext'
// import en from '../locales/en.json'
// import fr from '../locales/fr.json'
import styles from '../styles/Home.module.css'
// import { tType } from '../types'

const Home: NextPage = () => {

  const t = useAppContext()

  return (
    <div className={styles.container}>
      <Head>
        <title>Next JS Internationalized Routing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      </main>

    </div>
  )
}

export default Home
