name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: next-multilingual  # set this to the name of your Azure Web App

on:
  push:
    branches:
      - "main"

permissions:
  contents: 'read'
  packages: 'write'

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ secrets.IMAGE }}
